apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
  annotations:
    workflows.argoproj.io/default-artifact-repository: artifactRepository
data:
  artifactRepository: |
    s3:
      bucket: s3-1321722407
      endpoint: s3-1321722407.cos.ap-beijing.myqcloud.com
      insecure: false
      accessKeySecret:
        name: cos-credentials
        key: accesskey
      secretKeySecret:
        name: cos-credentials
        key: secretkey
      region: ap-beijing
      keyFormat: "artifacts/{{workflow.name}}"  # 指定存储路径 比如：artifacts/my-artifact-name
      archiveStrategy:
        none: {}  # 设置全局默认不打包