apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: steps-
spec:
  entrypoint: hello-hello-hello

  # This spec contains two templates: hello-hello-hello and print-message
  templates:
  - name: hello-hello-hello
    # Instead of just running a container
    # This template has a sequence of steps
    steps:
    - - name: hello1            # hello1 is run before the following steps
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "hello1"
    - - name: hello2a         
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "hello2a"
      - name: hello2b          
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "hello2b"
      - name: hello2c           
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "hello2c"
      - name: hello2d           
        template: print-message
        arguments:
          parameters:
          - name: message
            value: "hello2d"
 
  # This is the same template as from the previous example
  - name: print-message
    inputs:
      parameters:
      - name: message
    container:
      image: busybox
      imagePullPolicy: IfNotPresent
      command: [echo]
      args: ["{{inputs.parameters.message}}"]