apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: helloworld
spec:
  entrypoint: main
  templates:
  - name: main
    container:
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command: [echo, "Hello, Argo!"]